-- SQL Example by Jeremy Gallen

drop DATABASE BMS_DB;

create DATABASE BMS_DB1;

use BMS_DB1;

show databases;

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
	CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);

SHOW TABLES;

-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
	CUSTOMER_ID VARCHAR(5)
)